/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ThreadContactIdRouteImport } from './routes/thread.$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadContactIdRoute = ThreadContactIdRouteImport.update({
  id: '/thread/$contactId',
  path: '/thread/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/thread/$contactId': typeof ThreadContactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/thread/$contactId': typeof ThreadContactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/capture': typeof CaptureRoute
  '/people': typeof PeopleRoute
  '/settings': typeof SettingsRoute
  '/thread/$contactId': typeof ThreadContactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/capture' | '/people' | '/settings' | '/thread/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/capture' | '/people' | '/settings' | '/thread/$contactId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/capture'
    | '/people'
    | '/settings'
    | '/thread/$contactId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CaptureRoute: typeof CaptureRoute
  PeopleRoute: typeof PeopleRoute
  SettingsRoute: typeof SettingsRoute
  ThreadContactIdRoute: typeof ThreadContactIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$contactId': {
      id: '/thread/$contactId'
      path: '/thread/$contactId'
      fullPath: '/thread/$contactId'
      preLoaderRoute: typeof ThreadContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CaptureRoute: CaptureRoute,
  PeopleRoute: PeopleRoute,
  SettingsRoute: SettingsRoute,
  ThreadContactIdRoute: ThreadContactIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
